server:
  port: 8082

spring:
  application:
    name: room-service
  datasource:
    url: jdbc:postgresql://room-db:5432/room_db
    username: room_user
    password: room_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: redis
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true

app:
  events:
    topic: room-events