server:
  port: 8084

spring:
  application:
    name: reporting-service
  data:
    mongodb:
      uri: mongodb://mongo:27017/reporting_db
    redis:
      host: redis
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true

app:
  events:
    channel: reporting-events